; see http://haraka.github.io/core/Outbound

; disabled (default: false)
; disabled=true

; concurrency_max (default: 100)
concurrency_max=100

; enable_tls=false

; received_header (default: "Haraka outbound")
received_header=RelayStack outbound

; inet_prefer (default: default)
inet_prefer=v4
